### ISSUE TITLE
exposures should only lead to asymptomatic infections

### ISSUE THREAD

**Issue by griswaldbrooks** [kestrel-labs/superspreader#36]
### Need

_In order to_ allow players to go through the normal infection progression
_As a_ player
_I want to_ become asymptomatic even when receiving a large number of exposures.

### Acceptance Criteria

**Scenario:** exposures should only lead to asymptomatic infections
**GIVEN** a number of exposures greater than required to lead to infection
**WHEN** exposed all a once to a healthy player
**THEN** they should transition to `INFECTED_ASYM`

### Definition of Done
- [ ] Unit or integration tests added
- [ ] Pull request merged
- [ ] Acceptance/Simulation testing done

### Tasks

- [ ] Refactor `exposure_update` to limit healthy player state transistion to `INFECTED_ASYM`

### Notes

References:
There is a defect in this function where a high number of exposures at one time when healthy can transition you to late stage infection.
https://github.com/kestrel-labs/superspreader/blob/main/arduino/health_monitor/health_monitor_core.cpp#L9-L14
